## Unified config for nudeploy (save as ./nudeploy.toml)

[[downloads]]
name = "openobserve"
version = "v0.15.0-rc5"
url = "https://downloads.openobserve.ai/releases/openobserve/v0.15.0-rc4/openobserve-v0.15.0-rc4-linux-amd64.tar.gz"
enable = true
dst_dir = "/tmp"
extract = true

[[copy]]
name = "serve"
src = "/home/akagi201/src/github.com/Akagi201/serve-rs/target/release/serve"
dst = "/home/akagi201/serve/bin/serve"
enable = true

[[hosts]]
name = "localhost"
ip = "127.0.0.1"
port = 22
user = "akagi201"
enable = true
group = "prod"

[[services]]
name = "serve"
src_dir = "./serve"
dst_dir = "/home/akagi201/serve"
unit_file = "serve.service"
sync_files = [
	{ from = "serve.env", to = "serve.env" },
]
restart = true
enable = true
